// Valid guess words are in validWords.js (auto-generated from the Wordle word list)
// Words that can be the answer
export const ANSWERS = [
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult',
  'after', 'again', 'agent', 'agree', 'ahead', 'alarm', 'album', 'alert',
  'alike', 'alive', 'alley', 'allow', 'alone', 'along', 'angel', 'anger',
  'angle', 'angry', 'ankle', 'annex', 'apart', 'apple', 'apply', 'arena',
  'argue', 'arise', 'armor', 'array', 'aside', 'audio', 'audit', 'avoid',
  'awake', 'award', 'aware', 'awful', 'baker', 'basic', 'basis', 'batch',
  'beach', 'beard', 'beast', 'began', 'begin', 'being', 'below', 'bench',
  'berry', 'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'blaze',
  'blend', 'bless', 'blind', 'block', 'blood', 'bloom', 'blown', 'blunt',
  'board', 'boost', 'booth', 'bound', 'brace', 'brain', 'brand', 'brave',
  'bread', 'break', 'brick', 'bride', 'brief', 'bring', 'broad', 'broke',
  'brook', 'brown', 'build', 'built', 'burst', 'buyer', 'cabin', 'cable',
  'candy', 'carry', 'catch', 'cause', 'chalk', 'chaos', 'charm', 'chart',
  'chase', 'cheap', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chief',
  'child', 'chill', 'claim', 'clash', 'class', 'clean', 'clear', 'click',
  'climb', 'clock', 'clone', 'close', 'cloud', 'coast', 'could', 'count',
  'court', 'cover', 'craft', 'crash', 'crazy', 'cream', 'creek', 'crime',
  'crisp', 'cross', 'crowd', 'crown', 'crush', 'curve', 'cycle', 'daily',
  'dance', 'death', 'decay', 'delay', 'dense', 'depot', 'depth', 'dirty',
  'doubt', 'dough', 'draft', 'drain', 'drama', 'drawn', 'dream', 'drift',
  'drink', 'drive', 'drove', 'drunk', 'eagle', 'early', 'earth', 'eight',
  'elite', 'empty', 'enemy', 'enjoy', 'enter', 'entry', 'equal', 'error',
  'essay', 'event', 'every', 'exact', 'exist', 'extra', 'faint', 'faith',
  'false', 'fancy', 'fatal', 'fault', 'feast', 'fence', 'fight', 'final',
  'fixed', 'flame', 'flash', 'float', 'floor', 'focus', 'force', 'forge',
  'forth', 'found', 'frame', 'frank', 'fraud', 'fresh', 'front', 'frost',
  'fruit', 'fully', 'funny', 'ghost', 'giant', 'given', 'glass', 'globe',
  'gloom', 'glove', 'going', 'grace', 'grade', 'grand', 'grant', 'graph',
  'grasp', 'grass', 'grave', 'great', 'green', 'grief', 'grind', 'groan',
  'gross', 'group', 'grove', 'grown', 'guard', 'guest', 'guide', 'guilt',
  'happy', 'harsh', 'heart', 'heavy', 'herbs', 'hinge', 'hobby', 'honey',
  'honor', 'horse', 'hotel', 'house', 'human', 'humor', 'hurry', 'image',
  'imply', 'index', 'input', 'issue', 'joint', 'joker', 'joust', 'judge',
  'juice', 'juicy', 'karma', 'knack', 'knife', 'knock', 'known', 'label',
  'labor', 'lance', 'large', 'laser', 'latch', 'later', 'laugh', 'layer',
  'learn', 'least', 'leave', 'legal', 'level', 'light', 'limit', 'local',
  'lodge', 'logic', 'loose', 'lower', 'lucky', 'lunar', 'lyric', 'magic',
  'major', 'manor', 'maple', 'march', 'match', 'maybe', 'mayor', 'media',
  'mercy', 'merit', 'metal', 'might', 'minor', 'minus', 'model', 'money',
  'month', 'moral', 'motor', 'mount', 'mouse', 'mouth', 'movie', 'music',
  'nerve', 'never', 'night', 'noise', 'north', 'noted', 'novel', 'nurse',
  'occur', 'ocean', 'offer', 'often', 'olive', 'onset', 'opera', 'order',
  'other', 'ought', 'outer', 'oxide', 'ozone', 'paint', 'panel', 'panic',
  'paper', 'party', 'pasta', 'patch', 'pause', 'peace', 'pearl', 'penny',
  'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pixel', 'pizza',
  'place', 'plain', 'plane', 'plant', 'plate', 'plaza', 'point', 'poker',
  'polar', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior',
  'prize', 'probe', 'proof', 'prose', 'proud', 'prove', 'queen', 'query',
  'quest', 'queue', 'quick', 'quiet', 'quota', 'quote', 'radar', 'radio',
  'raise', 'ranch', 'range', 'rapid', 'ratio', 'reach', 'realm', 'rebel',
  'refer', 'reign', 'relax', 'reply', 'rider', 'ridge', 'right', 'risky',
  'rival', 'river', 'rocky', 'round', 'route', 'royal', 'rugby', 'ruler',
  'rumor', 'rural', 'salad', 'sauce', 'scale', 'scene', 'scope', 'score',
  'seize', 'sense', 'serve', 'setup', 'seven', 'shake', 'shall', 'shame',
  'shape', 'share', 'shark', 'sharp', 'shell', 'shift', 'shine', 'shirt',
  'shock', 'shore', 'short', 'shout', 'shove', 'sight', 'since', 'sixth',
  'sixty', 'skill', 'skull', 'slate', 'sleep', 'slice', 'slide', 'slope',
  'small', 'smart', 'smell', 'smile', 'smoke', 'solid', 'solve', 'sorry',
  'south', 'space', 'spare', 'spark', 'speak', 'speed', 'spend', 'spice',
  'spill', 'spine', 'split', 'spoke', 'spoon', 'sport', 'spray', 'squad',
  'stack', 'staff', 'stage', 'stain', 'stake', 'stale', 'stand', 'stark',
  'start', 'state', 'steam', 'steel', 'steep', 'steer', 'stern', 'stick',
  'stiff', 'still', 'stock', 'stole', 'stone', 'stood', 'store', 'storm',
  'story', 'strap', 'straw', 'strip', 'style', 'sugar', 'super', 'swamp',
  'swear', 'sweep', 'sweet', 'swept', 'swift', 'swipe', 'swirl', 'sword',
  'swore', 'sworn', 'table', 'taste', 'teach', 'teeth', 'tense', 'terms',
  'thank', 'their', 'there', 'these', 'thick', 'thing', 'think', 'thorn',
  'those', 'three', 'threw', 'throw', 'tiger', 'tight', 'timer', 'tired',
  'title', 'today', 'token', 'topic', 'total', 'touch', 'tough', 'tower',
  'toxic', 'track', 'trade', 'trail', 'train', 'trait', 'trash', 'tread',
  'treat', 'trend', 'trial', 'tribe', 'tried', 'troop', 'trove', 'truck',
  'truly', 'trust', 'truth', 'tumor', 'twist', 'ultra', 'under', 'union',
  'until', 'upper', 'upset', 'urban', 'usage', 'usual', 'utter', 'valid',
  'value', 'valve', 'vapor', 'vault', 'verse', 'video', 'vigor', 'viral',
  'virus', 'visit', 'vista', 'vital', 'vivid', 'vocal', 'vodka', 'voice',
  'voter', 'wager', 'waste', 'watch', 'water', 'weary', 'weave', 'wedge',
  'weird', 'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'white',
  'whole', 'whose', 'wider', 'witch', 'woman', 'world', 'worry', 'worse',
  'worst', 'worth', 'would', 'wrath', 'write', 'wrote', 'yacht', 'yield',
  'young', 'yours', 'youth', 'zebra', 'zoned',
]


export function getRandomAnswer() {
  return ANSWERS[Math.floor(Math.random() * ANSWERS.length)]
}
